### ISSUE TITLE
add a nice icon to the dlang bot

### ISSUE THREAD

**Issue by wilzbach** [MartinNowak/dlang-bot#1]
e.g. the D-man

![image](https://cloud.githubusercontent.com/assets/4370550/17459539/8e014474-5c3c-11e6-87b8-4dffa8ce8fac.png)

If you want to pick a special one -> https://github.com/wilzbach/d-mans
Here are some ideas:

![20160506_005](https://cloud.githubusercontent.com/assets/4370550/17459526/4537ef18-5c3c-11e6-89f7-6c05638d5c28.jpg)
![20160515_001](https://cloud.githubusercontent.com/assets/4370550/17459532/54929792-5c3c-11e6-995f-f16a084c70a7.jpg)
![20160510_013](https://cloud.githubusercontent.com/assets/4370550/17459528/4b8eee16-5c3c-11e6-8b64-66d033012050.jpg)
![20160525_001](https://cloud.githubusercontent.com/assets/4370550/17459534/60a88ae6-5c3c-11e6-86fd-0b125607f239.jpg)
![20160528_009](https://cloud.githubusercontent.com/assets/4370550/17459535/68c6cd78-5c3c-11e6-9a37-ce2915dca023.jpg)
![20160419_006](https://cloud.githubusercontent.com/assets/4370550/17459538/7e230de4-5c3c-11e6-92bf-a9b0f4bdcb0e.jpg)

**Comment by MartinNowak** [comment]
That one is great, looks like a bot.
https://wilzbach.github.io/d-mans//meiz/20160528_009.jpg

**Comment by wilzbach** [comment]
> That one is great, looks like a bot.
> https://wilzbach.github.io/d-mans//meiz/20160528_009.jpg

I like it too ;-)

**Comment by wilzbach** [comment]
Thanks!
