### ISSUE TITLE
Trigger daily rebuilds

### ISSUE THREAD

**Issue by wilzbach** [MartinNowak/dlang-bot#12]
For example the tools repo got broken with the 2.072 release due, so it would be nice to ensure everything is working. 
Idk if retriggering the last build would work because afaik then only the person who merged the PR gets notified (this  could be solved by posting to the mailing list) and if it's daily it could get spammy in case of an error (imho that's wanted).

We could use on of these ping monitors / free cron job services out there and run a special route once a day (or twice).

**Comment by MartinNowak** [comment]
Let's not conflate CI testing with a website bot. Also ex post notifications that something broke tend to not work out for CI, we need to test before merging stuff.
