### ISSUE TITLE
check issue title for issue references too

### ISSUE THREAD

**Issue by wilzbach** [MartinNowak/dlang-bot#7]
It seems to be common for newcomers to use "short" git commit messages that don't reflect the issue.
A fix for this could be
1) to check the PR title for issue references too as other people could change the title
2) write them that if a title contains the word issue or fix that the syntax is wrong

https://github.com/dlang/phobos/pull/4702
https://github.com/dlang/phobos/pull/4740

**Comment by MartinNowak** [comment]
Nope, people need to adjust their behavior (do we have that in CONTRIBUTING.md?).
It's necessary for automation to track issues on a git not on a github level, e.g. github's Bugzilla integration and our changelog tool rely on that.
